### ISSUE TITLE
Schematica is not recognising the file

### ISSUE THREAD

**Issue by WolligesSchaf** [GoldenDelicios/Lite2Edit#11]

**Comment by GoldenDelicios** [comment]
Hey there, it seems you're trying to use the exported schematic with Schematica, which to my knowledge uses the old format for 1.12 and below (version 1 of the Sponge schematic format specification). Lite2Edit produces version 2 of the format, which works for WorldEdit for Minecraft 1.13+.

You might be able to try converting the .schem file to the legacy .schematic using this resources here: https://puregero.github.io/SchemToSchematic/
