### ISSUE TITLE
Program not opening

### ISSUE THREAD

**Issue by Hamude995** [GoldenDelicios/Lite2Edit#8]
Every time I try to open it no gui pops up. I've even tried different versions.

**Comment by CodeByAidan** [comment]
Well this isn't really that useful information. No screenshots or attempt videos? Regardless, do you have a Java runtime? Did you try opening it with a Java 8+ OpenJDK Platform binary?

**Comment by GoldenDelicios** [comment]
Closing this issue as it is stale. If this problem persists, feel free to open another issue.
