### ISSUE TITLE
CLI API

### ISSUE THREAD

**Issue by Regela** [GoldenDelicios/Lite2Edit#9]
Please add CLI API. It is necessary to add a -help argument to indicate how to use it and the ability to redo schematics without launching the GUI. Thank you )

**Comment by joestr** [comment]
Yeah a CLI would be nice!

**Comment by emeraldtip** [comment]
I might do it if I have time

**Comment by emeraldtip** [comment]
Is done
I've published a release [here](https://github.com/emeraldtip/Lite2Edit/releases/tag/v1.2), check the README for instructions

I've also opened a [pull request](https://github.com/GoldenDelicios/Lite2Edit/pull/10) to get the changes into the main repo

**Comment by GoldenDelicios** [comment]
Thanks for your help @emeraldtip. I've published release 1.2 which includes this feature.

**Comment by AnhDVCoding** [comment]
> Is done I've published a release [here](https://github.com/emeraldtip/Lite2Edit/releases/tag/v1.2), check the README for instructions
> 
> I've also opened a [pull request](https://github.com/GoldenDelicios/Lite2Edit/pull/10) to get the changes into the main repo

Hi, I try the CLI but didn't work, it just kept opened the GUI up but not convert any file, can u check please?

**Comment by AnhDVCoding** [comment]
nvm, i checked the source code and the correct CLI is "java -jar Lite2Edit-1.2.0.jar --cli test.litematic"
